version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password_fuchibol
      - MYSQL_DATABASE=simulador_futbol
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local