version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DB_PASSWORD_ROOT
      - MYSQL_DATABASE=$MYSQL_DB
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql
  app:
    container_name: node_app
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  db_data:
    driver: local